import type { FormField } from "@/lib/domain/types";
import { isAnswerable } from "@/lib/domain/types";

/**
 * Batch 3w - a completed form as a clean A4 document. Same zero-dependency
 * pattern as the table exports: build print-styled HTML, open it, and the OS
 * print dialog saves it as PDF. The builder is pure so escaping and layout
 * are unit-tested; both the practice (form responses, waitlist answers) and
 * the client (their own completed forms in /me) download through it.
 */

export interface ResponsePdfInput {
  formTitle: string;
  /** The practice's name - printed under the title. */
  orgName?: string | null;
  /** Who answered, when known. */
  respondent?: string | null;
  submittedAt?: string | null;
  fields: FormField[];
  answers: Record<string, string>;
}

const esc = (v: string) =>
  v.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

function fullDate(iso: string): string {
  return new Intl.DateTimeFormat("en-ZA", { timeZone: "Africa/Johannesburg", day: "numeric", month: "long", year: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(iso));
}

/** The complete printable document, as HTML. Pure - no window access. */
export function buildResponsePdfHtml(input: ResponsePdfInput): string {
  const subtitle = [
    input.respondent ? `Answered by ${input.respondent}` : null,
    input.submittedAt ? `Submitted ${fullDate(input.submittedAt)}` : null,
    input.orgName ?? null,
  ].filter(Boolean).join(" · ");

  const body = input.fields
    .map((f) => {
      if (f.type === "section") {
        return `<h2>${esc(f.label || "")}</h2>`;
      }
      if (!isAnswerable(f.type)) return "";
      const answer = (input.answers[f.id] ?? "").trim();
      return `<div class="qa"><div class="q">${esc(f.label || "Untitled question")}</div><div class="a${answer ? "" : " empty"}">${answer ? esc(answer).replace(/\n/g, "<br>") : "-"}</div></div>`;
    })
    .join("\n");

  return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(input.formTitle)}</title>
<style>
  * { box-sizing: border-box; }
  body { font: 12.5px/1.55 system-ui, -apple-system, "Segoe UI", sans-serif; color: #1a1f1c; margin: 30px; max-width: 720px; }
  h1 { font-size: 19px; margin: 0 0 2px; }
  .sub { color: #6b7570; font-size: 11.5px; margin-bottom: 18px; }
  h2 { font-size: 11px; text-transform: uppercase; letter-spacing: .05em; color: #6b7570; border-bottom: 1.5px solid #d8ded9; padding-bottom: 4px; margin: 20px 0 8px; }
  .qa { page-break-inside: avoid; margin-bottom: 11px; }
  .q { font-weight: 600; font-size: 12px; }
  .a { margin-top: 1px; white-space: pre-wrap; }
  .a.empty { color: #9aa39d; }
  .foot { margin-top: 26px; padding-top: 8px; border-top: 1px solid #e7ece8; color: #9aa39d; font-size: 10.5px; }
  @page { margin: 16mm; }
</style></head><body>
<h1>${esc(input.formTitle)}</h1>
${subtitle ? `<div class="sub">${esc(subtitle)}</div>` : ""}
${body}
<div class="foot">Kept confidential under POPIA. Generated by Phila.</div>
<script>window.onload = () => { window.print(); };</script>
</body></html>`;
}

/** Open the document in a print window - the browser's dialog saves it as PDF. */
export function downloadResponsePdf(input: ResponsePdfInput): void {
  const url = URL.createObjectURL(new Blob([buildResponsePdfHtml(input)], { type: "text/html" }));
  window.open(url, "_blank", "width=900,height=700");
  setTimeout(() => URL.revokeObjectURL(url), 60_000);
}
